title: David Lluberes Cloud Engineer
author: David Lluberes
email: davidk21@pm.me
theme: minima
description: Online Resume

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
